version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY:-d05053f665ff724fddd1ec75fc8f5071}
      - VISUAL_CROSSING_API_KEY=${VISUAL_CROSSING_API_KEY:-8L4Y4RLAT733984N2Y79EVHRQ}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
